In [36]:
import pandas as pd
import numpy as np
import plotly.graph_objs as go 
from plotly.offline import init_notebook_mode,iplot
import matplotlib.pyplot as plt
import plotly.figure_factory as ff
import math
init_notebook_mode(connected=True) 
%matplotlib inline

In [2]:
path = '/Users/shmylm/Desktop/Project/fetched/'

In [3]:
LA = pd.read_csv(path + 'business analyst-Los Angeles-job-results-desc.csv')

In [4]:
Houston = pd.read_csv(path + 'business analyst-Houston-job-results-desc.csv')

In [5]:
Phoneix = pd.read_csv(path + 'business analyst-Phoenix-job-results-desc.csv')

In [6]:
San_Diego = pd.read_csv(path + 'business analyst-San Diego-job-results-desc.csv')

In [7]:
San_Jose = pd.read_csv(path + 'business analyst-San Jose-job-results-desc.csv')

In [8]:
Austin = pd.read_csv(path + 'business analyst-Austin-job-results-desc.csv')

In [9]:
Fort_Worth = pd.read_csv(path + 'business analyst-Fort Worth-job-results-desc.csv')

In [10]:
BA_job = pd.concat([LA, Houston, Phoneix, San_Diego, San_Jose, Austin, Fort_Worth], ignore_index=True)

In [11]:
# BA_job.to_csv('merge.csv')

In [12]:
#Check whether merge correctly or not
len(LA)+len(Houston)+len(Phoneix)+len(San_Diego)+len(San_Jose)+len(Austin)+len(Fort_Worth)

4646

In [13]:
import plotly.plotly as py
import plotly.tools as tls

In [14]:
city_dict={}
for i in range(len(BA_job['City'])):
    if BA_job['City'][i] not in city_dict:
        city_dict[BA_job['City'][i]] = 1
    else:
        city_dict[BA_job['City'][i]] += 1

In [15]:
state_dict={}
for i in range(len(BA_job['State'])):
    if BA_job['State'][i] not in state_dict:
        state_dict[BA_job['State'][i]] = 1
    else:
        state_dict[BA_job['State'][i]] += 1

In [16]:
state_dict['CA']=state_dict['CA']+4

In [17]:
state=[]
for i in state_dict.keys():
    state.append(i)

In [18]:
counts=[]
for i in state_dict.values():
    counts.append(i)

In [19]:
state=pd.DataFrame({'State':state,'Counts':counts})

In [20]:
state

         State  Counts
0           CA    1616
1  Los Angeles       3
2           TX    2170
3           AZ     860
4    San Diego       1

In [27]:
BA_job.head()

,Name,Company,City,State,Salary,Description,Url
0,Business Intelligence Analyst,CBS Interactive,Burbank,CA,$63k-$86k(Glassdoor Est.),Business Intelligence Analyst Apply Ref#: 321...,https://www.glassdoor.com/partner/jobListing.h...
1,Business Intelligence Analyst,Verve,Los Angeles,CA,NaN,Verve-BIAnalyst-LA - Business Intelligence An...,https://www.glassdoor.com/partner/jobListing.h...
2,Business Analyst,InvestCloud,Los Angeles,CA,$92k-$144k(Glassdoor Est.),Job DescriptionPosition Overview InvestCloud ...,https://www.glassdoor.com/partner/jobListing.h...
3,Business Analyst,Irvine Technology Corporation,Los Angeles,CA,$66k-$107k(Glassdoor Est.),Job Description**NEW** Business Analyst- 6 mo...,https://www.glassdoor.com/partner/jobListing.h...
4,Business Analyst,Civic Financial Services,Redondo Beach,CA,$60k-$97k(Glassdoor Est.),Founded in 2014 by it’s parent companies Wedg...,https://www.glassdoor.com/partner/jobListing.h...

In [29]:
#clean data in salary column which have hourly rate instead of yearly
def modify_data(df):
    count = 0
    for i in range(len(df['Salary'])):
        if type(df['Salary'][i]) != str:
            if math.isnan(df['Salary'][i]) == True:
                df['Salary'][i] = df['Salary'][i]
        elif 'per hour' not in df['Salary'][i]:
            df['Salary'][i] = df['Salary'][i]
        elif 'per hour' in df['Salary'][i]:
            l = int(int(df['Salary'][i][1:3])*40*4*12/1000)
            u = int(int(df['Salary'][i][5:7])*40*4*12/1000)
            df['Salary'][i] = '$'+str(l) + 'k' + '-' + '$' + str(u) + 'k'
    return df

In [30]:
new_BA = modify_data(BA_job)

In [31]:
new_BA['Salary'][1758]

'$32k-$48k'

In [32]:
def get_range(df):
    lower = []
    upper = []
    for i in range(len(df['Salary'])):
        if type(df['Salary'][i]) != str:
            if math.isnan(df['Salary'][i]) == True:
                lower.append(None)
                upper.append(None)
        else:
            salary = df['Salary'][i]
            salary = salary.split('k')
            lower.append(salary[0][1:])
            upper.append(salary[1][2:])
    return lower,upper

In [33]:
get_range(new_BA)

(['63',
  None,
  '92',
  '66',
  '60',
  '49',
  '74',
  '80',
  '55',
  '45',
  '75',
  '68',
  '66',
  '64',
  None,
  None,
  '48',
  None,
  '58',
  None,
  '77',
  None,
  None,
  '53',
  '70',
  '73',
  '75',
  None,
  '51',
  None,
  '62',
  None,
  None,
  '63',
  None,
  None,
  '59',
  None,
  '64',
  '66',
  None,
  '50',
  '55',
  '80',
  '55',
  None,
  None,
  '101',
  '45',
  None,
  '49',
  None,
  None,
  None,
  '73',
  '65',
  '52',
  None,
  None,
  '66',
  '64',
  '51',
  None,
  '67',
  '73',
  '56',
  '53',
  '54',
  None,
  None,
  '65',
  None,
  None,
  '51',
  '33',
  '49',
  None,
  '62',
  None,
  None,
  '59',
  None,
  '58',
  None,
  None,
  None,
  '49',
  '54',
  None,
  '117',
  None,
  None,
  None,
  '59',
  None,
  '50',
  '66',
  '72',
  '69',
  '69',
  '51',
  None,
  None,
  '53',
  '69',
  None,
  None,
  None,
  '40',
  None,
  '90',
  '50',
  '69',
  None,
  None,
  '35',
  None,
  None,
  None,
  '71',
  '82',
  '50',
  None,
  '42',
  None,
  None,
  '89',
  '75',
  '63',
  '55',
  '67',
  None,
  '53',
  '50',
  '63',
  '98',
  '45',
  '67',
  None,
  '58',
  None,
  '76',
  '87',
  '64',
  None,
  '54',
  '58',
  '49',
  '50',
  None,
  None,
  None,
  None,
  '59',
  '45',
  None,
  None,
  '39',
  '97',
  '93',
  '48',
  '67',
  None,
  '55',
  '45',
  '92',
  None,
  None,
  '61',
  '48',
  None,
  None,
  '64',
  '54',
  '62',
  '61',
  '85',
  '57',
  '93',
  None,
  None,
  '45',
  '76',
  '76',
  None,
  '72',
  None,
  None,
  '54',
  None,
  '64',
  None,
  None,
  '52',
  None,
  '69',
  '70',
  '63',
  '64',
  '89',
  '53',
  '44',
  '51',
  '64',
  None,
  None,
  '40',
  '55',
  None,
  None,
  '45',
  '88',
  '69',
  '69',
  '79',
  None,
  '53',
  None,
  None,
  '76',
  None,
  '53',
  '63',
  None,
  '65',
  None,
  '131',
  '81',
  '51',
  '61',
  '94',
  '67',
  None,
  None,
  None,
  '48',
  None,
  '40',
  None,
  '45',
  '69',
  '88',
  '45',
  None,
  None,
  None,
  '33',
  None,
  '45',
  None,
  '69',
  None,
  '44',
  None,
  None,
  '106',
  '46',
  '71',
  '57',
  None,
  '58',
  None,
  '80',
  '91',
  '84',
  '76',
  None,
  '70',
  None,
  '77',
  '45',
  '107',
  '56',
  '45',
  None,
  None,
  None,
  '66',
  None,
  '81',
  '69',
  None,
  None,
  '46',
  '57',
  '50',
  '41',
  '73',
  '52',
  '49',
  '74',
  '95',
  '57',
  '106',
  '63',
  '68',
  '46',
  '55',
  None,
  None,
  '50',
  None,
  None,
  None,
  '55',
  None,
  None,
  '49',
  '76',
  '76',
  None,
  '76',
  '59',
  '88',
  '69',
  '46',
  '77',
  '50',
  None,
  '36',
  '64',
  None,
  None,
  None,
  '56',
  None,
  '54',
  '81',
  None,
  '71',
  '93',
  None,
  '50',
  None,
  '87',
  '51',
  None,
  None,
  None,
  '80',
  '68',
  '68',
  '44',
  '50',
  '77',
  '66',
  None,
  None,
  '76',
  None,
  '76',
  '93',
  '71',
  None,
  '70',
  '80',
  '68',
  None,
  None,
  '95',
  '45',
  '65',
  '70',
  None,
  '82',
  '71',
  None,
  '50',
  '77',
  None,
  '74',
  '47',
  None,
  '101',
  '67',
  '77',
  '50',
  '58',
  '61',
  '77',
  '72',
  '57',
  '80',
  None,
  None,
  '69',
  None,
  None,
  '67',
  None,
  None,
  None,
  '71',
  None,
  '72',
  None,
  None,
  None,
  None,
  '82',
  None,
  None,
  '68',
  None,
  None,
  '91',
  '58',
  '84',
  None,
  '57',
  '51',
  '70',
  '88',
  '45',
  None,
  '100',
  '55',
  '65',
  '64',
  None,
  None,
  '80',
  '60',
  None,
  '82',
  '53',
  '89',
  None,
  '73',
  None,
  None,
  '46',
  '66',
  '73',
  None,
  '55',
  '64',
  None,
  '55',
  '73',
  None,
  None,
  '61',
  '86',
  None,
  '71',
  None,
  '72',
  None,
  None,
  None,
  '75',
  '69',
  None,
  None,
  None,
  None,
  '83',
  None,
  None,
  '87',
  '44',
  '57',
  None,
  None,
  '69',
  '72',
  '70',
  '84',
  None,
  None,
  '58',
  None,
  '56',
  '75',
  '67',
  '107',
  None,
  '61',
  '73',
  '70',
  '58',
  None,
  None,
  '51',
  None,
  None,
  None,
  None,
  None,
  '48',
  '49',
  None,
  '63',
  '75',
  '60',
  '56',
  '68',
  None,
  None,
  '58',
  '38',
  '73',
  '72',
  None,
  '67',
  '46',
  '49',
  None,
  '75',
  None,
  None,
  None,
  '72',
  None,
  None,
  None,
  None,
  None,
  '49',
  None,
  '46',
  '66',
  '73',
  '67',
  '64',
  '55',
  '95',
  None,
  None,
  '61',
  '86',
  None,
  '82',
  '62',
  '87',
  None,
  '49',
  '46',
  None,
  '69',
  None,
  None,
  None,
  None,
  '83',
  None,
  None,
  '61',
  None,
  '87',
  None,
  '69',
  '55',
  '70',
  '72',
  None,
  '71',
  '55',
  '42',
  '72',
  None,
  None,
  None,
  '67',
  '107',
  '64',
  None,
  None,
  None,
  '61',
  None,
  None,
  '51',
  None,
  None,
  None,
  None,
  None,
  None,
  '44',
  '57',
  None,
  '84',
  '59',
  None,
  None,
  '58',
  None,
  '43',
  '56',
  '69',
  '83',
  '45',
  None,
  '49',
  '48',
  None,
  '67',
  '73',
  '87',
  '58',
  '70',
  None,
  None,
  None,
  None,
  '80',
  '51',
  None,
  '58',
  None,
  '63',
  None,
  None,
  None,
  '90',
  '47',
  None,
  '49',
  '77',
  '53',
  '53',
  None,
  '53',
  '79',
  None,
  None,
  None,
  None,
  None,
  '61',
  None,
  '50',
  '48',
  '60',
  '45',
  None,
  None,
  '88',
  '80',
  '88',
  None,
  '80',
  '49',
  '55',
  None,
  '77',
  '58',
  None,
  None,
  '54',
  '58',
  None,
  None,
  '52',
  '65',
  '82',
  None,
  '54',
  '53',
  '70',
  '82',
  '72',
  '30',
  None,
  None,
  None,
  None,
  '65',
  '80',
  None,
  None,
  '54',
  None,
  '58',
  '101',
  '59',
  '48',
  '44',
  None,
  '45',
  '49',
  '99',
  '95',
  '45',
  '48',
  None,
  '131',
  None,
  '52',
  None,
  None,
  None,
  None,
  '65',
  '71',
  '68',
  None,
  '54',
  None,
  None,
  '82',
  '131',
  '53',
  '61',
  '72',
  '140',
  '66',
  None,
  '63',
  '42',
  '58',
  None,
  '58',
  '71',
  None,
  None,
  None,
  None,
  '65',
  None,
  '54',
  None,
  None,
  '68',
  '100',
  None,
  None,
  None,
  None,
  '54',
  '131',
  '59',
  '107',
  '72',
  '88',
  None,
  '60',
  '68',
  '76',
  '77',
  '64',
  None,
  None,
  None,
  None,
  '62',
  '67',
  '48',
  '72',
  None,
  None,
  '72',
  '86',
  '49',
  None,
  '56',
  None,
  None,
  '63',
  '53',
  '102',
  None,
  '78',
  None,
  '85',
  None,
  None,
  '75',
  '51',
  None,
  None,
  '83',
  None,
  '47',
  None,
  None,
  '63',
  None,
  None,
  None,
  '57',
  '74',
  None,
  None,
  '90',
  None,
  None,
  '52',
  '60',
  '51',
  '74',
  '75',
  '80',
  '46',
  '44',
  '90',
  None,
  None,
  None,
  None,
  None,
  '73',
  '63',
  '59',
  None,
  '30',
  None,
  '61',
  '70',
  None,
  None,
  '57',
  '41',
  None,
  '42',
  '45',
  '67',
  None,
  None,
  None,
  None,
  '49',
  '82',
  '51',
  '80',
  '76',
  None,
  '77',
  '61',
  '86',
  None,
  '56',
  None,
  None,
  None,
  '60',
  '51',
  '61',
  None,
  '69',
  '61',
  '66',
  '55',
  '64',
  '51',
  '49',
  None,
  '54',
  '91',
  '53',
  '65',
  None,
  '82',
  '55',
  None,
  '53',
  None,
  '61',
  '72',
  '55',
  '98',
  None,
  None,
  None,
  None,
  '51',
  '53',
  None,
  None,
  '85',
  '149',
  None,
  None,
  '63',
  '68',
  None,
  None,
  '69',
  '63',
  None,
  '82',
  '82',
  None,
  '41',
  None,
  '102',
  '59',
  '63',
  '74',
  '49',
  None,
  '45',
  '78',
  '58',
  '71',
  '61',
  None,
  '82',
  '55',
  '53',
  None,
  '72',
  None,
  '48',
  '86',
  None,
  None,
  None,
  None,
  None,
  None,
  '73',
  None,
  None,
  None,
  '49',
  None,
  None,
  '55',
  None,
  None,
  None,
  '77',
  '61',
  '52',
  None,
  '56',
  '62',
  None,
  '57',
  '62',
  '41',
  '105',
  None,
  '68',
  None,
  None,
  None,
  '72',
  '65',
  '53',
  '63',
  None,
  '47',
  '61',
  '65',
  '60',
  '81',
  '87',
  '63',
  None,
  '48',
  '111',
  None,
  None,
  None,
  None,
  '57',
  '81',
  '59',
  None,
  None,
  '61',
  None,
  '49',
  None,
  None,
  '93',
  None,
  '73',
  None,
  None,
  None,
  '97',
  '59',
  '55',
  '91',
  '62',
  '52',
  '37',
  '61',
  '53',
  '65',
  '93',
  '73',
  '58',
  '87',
  '75',
  '61',
  None,
  '67',
  '64',
  None,
  '66',
  '81',
  None,
  None,
  '52',
  ...],
 ['86',
  None,
  '144',
  '107',
  '97',
  '81',
  '120',
  '126',
  '89',
  '75',
  '121',
  '110',
  '107',
  '104',
  None,
  None,
  '78',
  None,
  '83',
  None,
  '123',
  None,
  None,
  '87',
  '114',
  '111',
  '120',
  None,
  '83',
  None,
  '100',
  None,
  None,
  '86',
  None,
  None,
  '96',
  None,
  '103',
  '103',
  None,
  '82',
  '91',
  '100',
  '87',
  None,
  None,
  '143',
  '75',
  None,
  '81',
  None,
  None,
  None,
  '116',
  '105',
  '84',
  None,
  None,
  '107',
  '101',
  '83',
  None,
  '90',
  '118',
  '89',
  '88',
  '91',
  None,
  None,
  '105',
  None,
  None,
  '83',
  '53',
  '80',
  None,
  '104',
  None,
  None,
  '96',
  None,
  '92',
  None,
  None,
  None,
  '81',
  '78',
  None,
  '181',
  None,
  None,
  None,
  '97',
  None,
  '82',
  '106',
  '108',
  '110',
  '111',
  '83',
  None,
  None,
  '87',
  '111',
  None,
  None,
  None,
  '59',
  None,
  '120',
  '82',
  '110',
  None,
  None,
  '57',
  None,
  None,
  None,
  '110',
  '101',
  '81',
  None,
  '70',
  None,
  None,
  '129',
  '116',
  '86',
  '75',
  '107',
  None,
  '74',
  '82',
  '103',
  '147',
  '77',
  '90',
  None,
  '80',
  None,
  '110',
  '138',
  '105',
  None,
  '84',
  '95',
  '80',
  '82',
  None,
  None,
  None,
  None,
  '95',
  '75',
  None,
  None,
  '55',
  '116',
  '120',
  '75',
  '107',
  None,
  '75',
  '77',
  '122',
  None,
  None,
  '83',
  '78',
  None,
  None,
  '105',
  '84',
  '87',
  '95',
  '134',
  '93',
  '123',
  None,
  None,
  '75',
  '110',
  '110',
  None,
  '107',
  None,
  None,
  '89',
  None,
  '88',
  None,
  None,
  '83',
  None,
  '110',
  '92',
  '96',
  '103',
  '129',
  '81',
  '152',
  '89',
  '103',
  None,
  None,
  '53',
  '75',
  None,
  None,
  '75',
  '113',
  '112',
  '104',
  '127',
  None,
  '85',
  None,
  None,
  '110',
  None,
  '88',
  '96',
  None,
  '87',
  None,
  '168',
  '108',
  '89',
  '83',
  '121',
  '105',
  None,
  None,
  None,
  '65',
  None,
  '53',
  None,
  '75',
  '112',
  '113',
  '156',
  None,
  None,
  None,
  '55',
  None,
  '156',
  None,
  '111',
  None,
  '152',
  None,
  None,
  '139',
  '68',
  '110',
  '89',
  None,
  '95',
  None,
  '110',
  '125',
  '122',
  '110',
  None,
  '112',
  None,
  '143',
  '75',
  '167',
  '92',
  '75',
  None,
  None,
  None,
  '107',
  None,
  '120',
  '113',
  None,
  None,
  '73',
  '90',
  '77',
  '71',
  '125',
  '69',
  '93',
  '119',
  '150',
  '93',
  '139',
  '103',
  '110',
  '68',
  '83',
  None,
  None,
  '77',
  None,
  None,
  None,
  '74',
  None,
  None,
  '80',
  '110',
  '110',
  None,
  '115',
  '96',
  '139',
  '92',
  '76',
  '96',
  '63',
  None,
  '65',
  '103',
  None,
  None,
  None,
  '92',
  None,
  '89',
  '120',
  None,
  '98',
  '120',
  None,
  '83',
  None,
  '143',
  '77',
  None,
  None,
  None,
  '100',
  '102',
  '108',
  '84',
  '83',
  '124',
  '106',
  None,
  None,
  '110',
  None,
  '118',
  '120',
  '105',
  None,
  '115',
  '113',
  '111',
  None,
  None,
  '141',
  '64',
  '96',
  '103',
  None,
  '126',
  '114',
  None,
  '82',
  '117',
  None,
  '118',
  '80',
  None,
  '133',
  '90',
  '123',
  '82',
  '91',
  '115',
  '117',
  '95',
  '89',
  '110',
  None,
  None,
  '111',
  None,
  None,
  '98',
  None,
  None,
  None,
  '114',
  None,
  '107',
  None,
  None,
  None,
  None,
  '101',
  None,
  None,
  '110',
  None,
  None,
  '125',
  '95',
  '122',
  None,
  '89',
  '69',
  '92',
  '140',
  '73',
  None,
  '129',
  '91',
  '85',
  '84',
  None,
  None,
  '121',
  '88',
  None,
  '139',
  '91',
  '129',
  None,
  '118',
  None,
  None,
  '68',
  '87',
  '106',
  None,
  '78',
  '87',
  None,
  '73',
  '118',
  None,
  None,
  '82',
  '117',
  None,
  '93',
  None,
  '110',
  None,
  None,
  None,
  '109',
  '95',
  None,
  None,
  None,
  None,
  '121',
  None,
  None,
  '114',
  '70',
  '79',
  None,
  None,
  '110',
  '95',
  '94',
  '107',
  None,
  None,
  '95',
  None,
  '75',
  '121',
  '108',
  '141',
  None,
  '81',
  '99',
  '94',
  '95',
  None,
  None,
  '75',
  None,
  None,
  None,
  None,
  None,
  '76',
  '66',
  None,
  '86',
  '104',
  '103',
  '87',
  '102',
  None,
  None,
  '91',
  '57',
  '118',
  '89',
  None,
  '91',
  '71',
  '65',
  None,
  '109',
  None,
  None,
  None,
  '116',
  None,
  None,
  None,
  None,
  None,
  '83',
  None,
  '68',
  '87',
  '106',
  '76',
  '87',
  '78',
  '135',
  None,
  None,
  '82',
  '117',
  None,
  '101',
  '80',
  '122',
  None,
  '81',
  '68',
  None,
  '95',
  None,
  None,
  None,
  None,
  '121',
  None,
  None,
  '91',
  None,
  '114',
  None,
  '110',
  '73',
  '94',
  '95',
  None,
  '93',
  '75',
  '63',
  '110',
  None,
  None,
  None,
  '108',
  '141',
  '106',
  None,
  None,
  None,
  '81',
  None,
  None,
  '75',
  None,
  None,
  None,
  None,
  None,
  None,
  '70',
  '79',
  None,
  '107',
  '80',
  None,
  None,
  '95',
  None,
  '70',
  '75',
  '91',
  '118',
  '68',
  None,
  '81',
  '74',
  None,
  '83',
  '99',
  '104',
  '95',
  '94',
  None,
  None,
  None,
  None,
  '114',
  '76',
  None,
  '79',
  None,
  '83',
  None,
  None,
  None,
  '114',
  '65',
  None,
  '65',
  '106',
  '80',
  '70',
  None,
  '101',
  '110',
  None,
  None,
  None,
  None,
  None,
  '89',
  None,
  '83',
  '83',
  '88',
  '77',
  None,
  None,
  '114',
  '107',
  '113',
  None,
  '100',
  '81',
  '88',
  None,
  '103',
  '88',
  None,
  None,
  '103',
  '95',
  None,
  None,
  '84',
  '96',
  '117',
  None,
  '89',
  '91',
  '99',
  '139',
  '107',
  '47',
  None,
  None,
  None,
  None,
  '85',
  '111',
  None,
  None,
  '75',
  None,
  '79',
  '145',
  '112',
  '75',
  '63',
  None,
  '77',
  '81',
  '134',
  '147',
  '77',
  '71',
  None,
  '176',
  None,
  '74',
  None,
  None,
  None,
  None,
  '90',
  '132',
  '89',
  None,
  '89',
  None,
  None,
  '127',
  '194',
  '102',
  '89',
  '116',
  '190',
  '101',
  None,
  '119',
  '61',
  '95',
  None,
  '88',
  '132',
  None,
  None,
  None,
  None,
  '86',
  None,
  '89',
  None,
  None,
  '89',
  '154',
  None,
  None,
  None,
  None,
  '91',
  '194',
  '95',
  '138',
  '116',
  '130',
  None,
  '91',
  '109',
  '102',
  '124',
  '105',
  None,
  None,
  None,
  None,
  '101',
  '104',
  '83',
  '110',
  None,
  None,
  '109',
  '112',
  '81',
  None,
  '83',
  None,
  None,
  '95',
  '81',
  '142',
  None,
  '103',
  None,
  '123',
  None,
  None,
  '104',
  '72',
  None,
  None,
  '131',
  None,
  '72',
  None,
  None,
  '88',
  None,
  None,
  None,
  '79',
  '119',
  None,
  None,
  '129',
  None,
  None,
  '65',
  '92',
  '72',
  '97',
  '107',
  '120',
  '68',
  '74',
  '114',
  None,
  None,
  None,
  None,
  None,
  '103',
  '104',
  '101',
  None,
  '47',
  None,
  '98',
  '99',
  None,
  None,
  '86',
  '56',
  None,
  '61',
  '69',
  '107',
  None,
  None,
  None,
  None,
  '81',
  '131',
  '77',
  '115',
  '122',
  None,
  '121',
  '100',
  '136',
  None,
  '91',
  None,
  None,
  None,
  '93',
  '84',
  '91',
  None,
  '101',
  '100',
  '107',
  '89',
  '101',
  '81',
  '81',
  None,
  '89',
  '144',
  '86',
  '105',
  None,
  '131',
  '89',
  None,
  '85',
  None,
  '99',
  '116',
  '89',
  '154',
  None,
  None,
  None,
  None,
  '83',
  '88',
  None,
  None,
  '134',
  '193',
  None,
  None,
  '87',
  '107',
  None,
  None,
  '110',
  '86',
  None,
  '112',
  '112',
  None,
  '65',
  None,
  '133',
  '92',
  '103',
  '114',
  '81',
  None,
  '71',
  '124',
  '95',
  '114',
  '100',
  None,
  '131',
  '91',
  '73',
  None,
  '116',
  None,
  '73',
  '136',
  None,
  None,
  None,
  None,
  None,
  None,
  '118',
  None,
  None,
  None,
  '81',
  None,
  None,
  '89',
  None,
  None,
  None,
  '117',
  '95',
  '84',
  None,
  '88',
  '99',
  None,
  '93',
  '99',
  '68',
  '164',
  None,
  '110',
  None,
  None,
  None,
  '116',
  '105',
  '86',
  '93',
  None,
  '73',
  '99',
  '100',
  '98',
  '123',
  '124',
  '93',
  None,
  '73',
  '168',
  None,
  None,
  None,
  None,
  '89',
  '108',
  '87',
  None,
  None,
  '99',
  None,
  '76',
  None,
  None,
  '147',
  None,
  '117',
  None,
  None,
  None,
  '127',
  '91',
  '83',
  '144',
  '99',
  '89',
  '62',
  '84',
  '86',
  '105',
  '148',
  '118',
  '87',
  '124',
  '109',
  '95',
  None,
  '108',
  '104',
  None,
  '107',
  '123',
  None,
  None,
  '78',
  ...])

In [34]:
BA_job['Salary_Lower_Bound']=get_range(new_BA)[0]
BA_job['Salary_Upper_Bound']=get_range(new_BA)[1]

In [35]:
BA_job

,Name,Company,City,State,Salary,Description,Url,Salary_Lower_Bound,Salary_Upper_Bound
0,Business Intelligence Analyst,CBS Interactive,Burbank,CA,$63k-$86k(Glassdoor Est.),Business Intelligence Analyst Apply Ref#: 321...,https://www.glassdoor.com/partner/jobListing.h...,63,86
1,Business Intelligence Analyst,Verve,Los Angeles,CA,NaN,Verve-BIAnalyst-LA - Business Intelligence An...,https://www.glassdoor.com/partner/jobListing.h...,None,None
2,Business Analyst,InvestCloud,Los Angeles,CA,$92k-$144k(Glassdoor Est.),Job DescriptionPosition Overview InvestCloud ...,https://www.glassdoor.com/partner/jobListing.h...,92,144
3,Business Analyst,Irvine Technology Corporation,Los Angeles,CA,$66k-$107k(Glassdoor Est.),Job Description**NEW** Business Analyst- 6 mo...,https://www.glassdoor.com/partner/jobListing.h...,66,107
4,Business Analyst,Civic Financial Services,Redondo Beach,CA,$60k-$97k(Glassdoor Est.),Founded in 2014 by it’s parent companies Wedg...,https://www.glassdoor.com/partner/jobListing.h...,60,97
5,Business Analyst,Los Angeles Dodgers LLC,Los Angeles,CA,$49k-$81k(Glassdoor Est.),Title: Business AnalystDepartment: Business De...,https://www.glassdoor.com/partner/jobListing.h...,49,81
6,Business Analyst (Contract Position),Sony PlayStation,Los Angeles,CA,$74k-$120k(Glassdoor Est.),PlayStation isn't just the Best Place to Play...,https://www.glassdoor.com/partner/jobListing.h...,74,120
7,Business Analyst,KGS,Los Angeles,CA,$80k-$126k(Glassdoor Est.),Manager is looking for a techno / functional ...,https://www.glassdoor.com/partner/jobListing.h...,80,126
8,Business Analyst,The Coffee Bean & Tea Leaf,Los Angeles,CA,$55k-$89k(Glassdoor Est.),Apply Now Business Analyst Home Office - 5700...,https://www.glassdoor.com/partner/jobListing.h...,55,89
9,Business Analyst,AXS,Los Angeles,CA,$45k-$75k(Glassdoor Est.),AXS is a company whose core values reflect a ...,https://www.glassdoor.com/partner/jobListing.h...,45,75
10,Business Analyst,Boingo,Los Angeles,CA,$75k-$121k(Glassdoor Est.),Business Analyst Boingo is seeking a passionat...,https://www.glassdoor.com/partner/jobListing.h...,75,121
11,Business Analyst,Sony Electronics,Marina del Rey,CA,$68k-$110k(Glassdoor Est.),"We look for the risk-takers, the collaborator...",https://www.glassdoor.com/partner/jobListing.h...,68,110
12,Business Analyst,TCW,Los Angeles,CA,$66k-$107k(Glassdoor Est.),OverviewThe Business Analyst is responsible f...,https://www.glassdoor.com/partner/jobListing.h...,66,107
13,Business Analyst,Walt Disney Company,Burbank,CA,$64k-$104k(Glassdoor Est.),We have created one of the most powerful bran...,https://www.glassdoor.com/partner/jobListing.h...,64,104
14,Business Analyst,KORE1 Technologies,Los Angeles,CA,NaN,"KORE1, a nationwide provider of staffing and ...",https://www.glassdoor.com/partner/jobListing.h...,None,None
15,Business Analyst,Robert Half Technology,Los Angeles,CA,NaN,Business Analyst - nbsp;Warehouse Management ...,https://www.glassdoor.com/partner/jobListing.h...,None,None
16,Business Analyst,Globe Life And Accident Insurance Company,Los Angeles,CA,$48k-$78k(Glassdoor Est.),Job DescriptionWe are Globe Life And Accident...,https://www.glassdoor.com/partner/jobListing.h...,48,78
17,Business Analyst,Optomi,Los Angeles,CA,NaN,Business Systems Analyst (Contract) Los Angele...,https://www.glassdoor.com/partner/jobListing.h...,None,None
18,Business Analyst,Cognizant,Los Angeles,CA,$58k-$83k(Glassdoor Est.),"Associating, discussing with key stake holder...",https://www.glassdoor.com/partner/jobListing.h...,58,83
19,Entry Level Business Analyst,"Staffigo Technical Services, LLC",Los Angeles,CA,NaN,Responsibilities:Work directly with client cus...,https://www.glassdoor.com/partner/jobListing.h...,None,None
20,Business Analyst,WASH Multifamily Laundry Systems,Los Angeles,CA,$77k-$123k(Glassdoor Est.),Requisition Number 18-0102 Post Date 9/4/2018...,https://www.glassdoor.com/partner/jobListing.h...,77,123
21,Business Analyst,JLM Strategic Talent Partners,Los Angeles,CA,NaN,"SPECIFIC RESPONSIBILITIES:Plan, organize and d...",https://www.glassdoor.com/partner/jobListing.h...,None,None
22,Business Analyst,"ConsultNet, LLC",Compton,CA,NaN,Be a part of the ConsultNet difference. As a ...,https://www.glassdoor.com/partner/jobListing.h...,None,None
23,Business Analyst,Tala,Santa Monica,CA,$53k-$87k(Glassdoor Est.),"Tala is looking for an inquisitive, self-dire...",https://www.glassdoor.com/partner/jobListing.h...,53,87
24,Business Analyst,Genuent,Glendale,CA,$70k-$114k(Glassdoor Est.),Genuent is hiring a Senior Business Analyst (...,https://www.glassdoor.com/partner/jobListing.h...,70,114
25,Business Analyst,Cambria Solutions,Los Angeles,CA,$73k-$111k(Glassdoor Est.),"The Company Founded in 2003, Cambria Solutio...",https://www.glassdoor.com/partner/jobListing.h...,73,111
26,Business Analyst,Primus Software Corporation,El Segundo,CA,$75k-$120k(Glassdoor Est.),Overall Purpose: Responsible for working acro...,https://www.glassdoor.com/partner/jobListing.h...,75,120
27,Business Analyst - Entry Level,"Staffigo Technical Services, LLC",Los Angeles,CA,NaN,JOB DESCRIPTION: A Business Analyst must have ...,https://www.glassdoor.com/partner/jobListing.h...,None,None
28,Business Analyst,Westlake Financial Services,Los Angeles,CA,$51k-$83k(Glassdoor Est.),Job DescriptionWestlake Financial Services is...,https://www.glassdoor.com/partner/jobListing.h...,51,83
29,Business Analyst,Eleven Recruiting,Los Angeles,CA,NaN,Summary: The Business Analyst position is res...,https://www.glassdoor.com/partner/jobListing.h...,None,None
...,...,...,...,...,...,...,...,...,...
4616,SQL/ETL Delivery Analyst (SQL/Learn New Tools),Targetbase,Irving,TX,NaN,"About Targetbase As a data-driven, strategic c...",https://www.glassdoor.com/partner/jobListing.h...,None,None
4617,Systems Analyst,Robert Half,Grand Prairie,TX,NaN,JOB SUMMARY: Primary responsibilities include...,https://www.glassdoor.com/partner/jobListing.h...,None,None
4618,Senior Collections Analyst,TXU Energy,Irving,TX,NaN,If you have what it takes to become part of t...,https://www.glassdoor.com/partner/jobListing.h...,None,None
4619,Merchandise Analyst,Motorsport Aftermarket Group,Coppell,TX,NaN,MAG Retail Group has built the largest team o...,https://www.glassdoor.com/partner/jobListing.h...,None,None
4620,Model Risk Validation Analyst,Citigroup,Irving,TX,$68k-$144k(Glassdoor Est.),"Review and validate new and existing, provide...",https://www.glassdoor.com/partner/jobListing.h...,68,144
4621,Financial Analyst - 2019 Summer Intern,Sabre Holdings Corporation,Southlake,TX,$69k-$93k(Glassdoor Est.),Req ID: 44228 Job Family: Intern Sabre is t...,https://www.glassdoor.com/partner/jobListing.h...,69,93
4622,Apps Support Sr. Analyst,Citibank,Irving,TX,$57k-$83k(Glassdoor Est.),"Primary Location: United States,Texas,IrvingEd...",https://www.glassdoor.com/partner/jobListing.h...,57,83
4623,Foreign Exchange Project Analyst / Scrum Produ...,U.S. Bank,Irving,TX,$80k-$98k(Glassdoor Est.),Provides project and analytical support to Fo...,https://www.glassdoor.com/partner/jobListing.h...,80,98
4624,Enterprise Delivery Analyst,Acara Solutions,Irving,TX,NaN,Acara Solutions is looking for Enterprise Del...,https://www.glassdoor.com/partner/jobListing.h...,None,None
4625,Innovative Automation Analyst,TXU Energy,Irving,TX,NaN,If you have what it takes to become part of t...,https://www.glassdoor.com/partner/jobListing.h...,None,None
4626,Senior Financial Analyst,Celanese International Corporation,Irving,TX,$79k-$103k(Glassdoor Est.),Overview? ? Do you want to be a part of a coo...,https://www.glassdoor.com/partner/jobListing.h...,79,103
4627,"Lead Financial Analyst, SEC Reporting",Stryker,Flower Mound,TX,$68k-$91k(Glassdoor Est.),Job Description Strykers Worldwide Reporting ...,https://www.glassdoor.com/partner/jobListing.h...,68,91
4628,NICE Recording & Communication Surveillance An...,Tata Consultancy Services (North America),Irving,TX,NaN,Job DescriptionMust have:Extensive technical ...,https://www.glassdoor.com/partner/jobListing.h...,None,None
4629,Credit Maintenance Lead Analyst,Citibank,Irving,TX,NaN,"Primary Location: United States,Texas,IrvingEd...",https://www.glassdoor.com/partner/jobListing.h...,None,None
4630,Apps Support Sr Analyst,Citibank,Irving,TX,$57k-$83k(Glassdoor Est.),"Primary Location: United States,Texas,IrvingEd...",https://www.glassdoor.com/partner/jobListing.h...,57,83
4631,Senior Data Analyst,"Iconma, L.L.C.",Irving,TX,NaN,"Senior Data Analyst Location: Irving, TX Du...",https://www.glassdoor.com/partner/jobListing.h...,None,None
4632,Senior Operations Cost Analyst,Flowserve,Irving,TX,$59k-$83k(Glassdoor Est.),Job Posting/Business Card Title Senior Operati...,https://www.glassdoor.com/partner/jobListing.h...,59,83
4633,Credit Maintenance Lead Analyst,Citi,Irving,TX,NaN,"Primary Location: United States,Texas,IrvingEd...",https://www.glassdoor.com/partner/jobListing.h...,None,None
4634,Fusion Engineer - Technical Analyst,Oracle,Irving,TX,$45k-$78k(Glassdoor Est.),"As a member of the Support organization, your...",https://www.glassdoor.com/partner/jobListing.h...,45,78
4635,Credit Maintenance Sr. Analyst,Citi,Irving,TX,NaN,"Primary Location: United States,Texas,IrvingEd...",https://www.glassdoor.com/partner/jobListing.h...,None,None
4636,Sr. IT Analyst,Protection 1,Irving,TX,$56k-$84k(Glassdoor Est.),Company Overview:The ADT Corporation (NYSE: AD...,https://www.glassdoor.com/partner/jobListing.h...,56,84
4637,"Enterprise Consulting and Process Design, Seni...",TD Ameritrade,Southlake,TX,NaN,The Enterprise Consulting and Process Deisgn S...,https://www.glassdoor.com/partner/jobListing.h...,None,None
4638,Digital Tech Program Management Analyst,Citi,Irving,TX,$35k-$126k(Glassdoor Est.),"Primary Location: United States,Texas,IrvingEd...",https://www.glassdoor.com/partner/jobListing.h...,35,126
4639,Database System Analyst,Vastika,Irving,TX,NaN,Current Openings Database System Analyst - 0...,https://www.glassdoor.com/partner/jobListing.h...,None,None
4640,QA Automation/Mobile Apps Analyst,"Levi, Ray & Shoup, Inc.",Irving,TX,$53k-$72k(Glassdoor Est.),LRS Consulting Services is seeking QA Automat...,https://www.glassdoor.com/partner/jobListing.h...,53,72
4641,Dialer Senior Technical Analyst,Citi,Irving,TX,$66k-$111k(Glassdoor Est.),"Primary Location: United States,Texas,IrvingEd...",https://www.glassdoor.com/partner/jobListing.h...,66,111
4642,Analyst Financial Cost,The Judge Group,Irving,TX,NaN,Job DescriptionJob # 583893 Industrial Manufa...,https://www.glassdoor.com/partner/jobListing.h...,None,None
4643,Sr Sales Analyst,Pixentia,Irving,TX,NaN,"Job Category: Sales Work Location: Irving, TX...",https://www.glassdoor.com/partner/jobListing.h...,None,None
4644,Financial Analyst/Manager,RMS Computer Corporation,Irving,TX,$58k-$78k(Glassdoor Est.),"Our client, a leading global financial servic...",https://www.glassdoor.com/partner/jobListing.h...,58,78
4645,Senior Programmer Analyst,ePace Technologies,Irving,TX,NaN,About this Position: Develop front end visual ...,https://www.glassdoor.com/partner/jobListing.h...,None,None

In [37]:
BA_job.to_csv('merge_ver2.csv')